// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'engine.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';




                abstract class TtsBridgeApiImplPlatform extends BaseApiImpl<TtsBridgeWire> {
                  TtsBridgeApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EngineRegistryHandlePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandlePtr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected EngineRegistryHandle dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(dynamic raw);

@protected EngineRegistryHandle dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(dynamic raw);

@protected RustStreamSink<AudioChunk> dco_decode_StreamSink_audio_chunk_Sse(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected AudioChunk dco_decode_audio_chunk(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected EngineRequest dco_decode_box_autoadd_engine_request(dynamic raw);

@protected double dco_decode_box_autoadd_f_32(dynamic raw);

@protected PiperBackendConfig dco_decode_box_autoadd_piper_backend_config(dynamic raw);

@protected int dco_decode_box_autoadd_u_32(dynamic raw);

@protected EngineBackend dco_decode_engine_backend(dynamic raw);

@protected EngineRequest dco_decode_engine_request(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected int dco_decode_i_16(dynamic raw);

@protected Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

@protected int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

@protected PiperBackendConfig dco_decode_piper_backend_config(dynamic raw);

@protected TtsState dco_decode_tts_state(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected EngineRegistryHandle sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(SseDeserializer deserializer);

@protected EngineRegistryHandle sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(SseDeserializer deserializer);

@protected RustStreamSink<AudioChunk> sse_decode_StreamSink_audio_chunk_Sse(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected AudioChunk sse_decode_audio_chunk(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected EngineRequest sse_decode_box_autoadd_engine_request(SseDeserializer deserializer);

@protected double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

@protected PiperBackendConfig sse_decode_box_autoadd_piper_backend_config(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

@protected EngineBackend sse_decode_engine_backend(SseDeserializer deserializer);

@protected EngineRequest sse_decode_engine_request(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected int sse_decode_i_16(SseDeserializer deserializer);

@protected Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

@protected PiperBackendConfig sse_decode_piper_backend_config(SseDeserializer deserializer);

@protected TtsState sse_decode_tts_state(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(EngineRegistryHandle self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(EngineRegistryHandle self, SseSerializer serializer);

@protected void sse_encode_StreamSink_audio_chunk_Sse(RustStreamSink<AudioChunk> self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_audio_chunk(AudioChunk self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_engine_request(EngineRequest self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_piper_backend_config(PiperBackendConfig self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

@protected void sse_encode_engine_backend(EngineBackend self, SseSerializer serializer);

@protected void sse_encode_engine_request(EngineRequest self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_i_16(int self, SseSerializer serializer);

@protected void sse_encode_list_prim_i_16_strict(Int16List self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

@protected void sse_encode_piper_backend_config(PiperBackendConfig self, SseSerializer serializer);

@protected void sse_encode_tts_state(TtsState self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class


        class TtsBridgeWire implements BaseWire {

            factory TtsBridgeWire.fromExternalLibrary(ExternalLibrary lib) =>
              TtsBridgeWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            TtsBridgeWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandlePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_tts_flutter_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandlePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandlePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_tts_flutter_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandle = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEngineRegistryHandlePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        